routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['middleware' => ['web','auth']], function(){
    

    Route::get('/', function(){
        //super-admin=1 admin=2 doctor=3 
        if(Auth::user()->admin ==1 || Auth::user()->admin == 3 ){
            $doctor = \App\Doctor::all()->count();
            // $department = \App\Department::all()->count();

            $line_charts_array = array();
            for($i = 1 ; $i<=8 ; $i++){
                $date = \Carbon\Carbon::now()->addDays($i);
                $appointment_count= \App\Appointment::where('date', $date->format('Y-m-d'))->count();
                $line_chart['period'] = $date->format('Y-m-d');
                $line_chart['appointments'] = $appointment_count;
                array_push($line_charts_array , $line_chart);

            }

        $line_charts = json_encode($line_charts_array);
                return view('home' , compact('doctor' , 'line_charts'));
        }
        elseif (Auth::user()->admin == 2 ) {
            $users['users']= \App\User::all();
            $doctor = \App\Doctor::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $department = \App\Department::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $appointment = \App\Appointment::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $firstaid =\App\Firstaid::all()->count();
            
            $line_charts_array = array();
                for($i = 1 ; $i<=8 ; $i++){
                    $date = \Carbon\Carbon::now()->addDays($i);
                    $appointment_count= \App\Appointment::where('hospital_id', Auth::user()->hospital_id)->where('date', $date->format('Y-m-d'))->count();
                    $line_chart['period'] = $date->format('Y-m-d');
                    $line_chart['appointments'] = $appointment_count;
                    array_push($line_charts_array , $line_chart);

                }

            $line_charts = json_encode($line_charts_array);
      

                return view('home', compact('users' , 'doctor' , 'firstaid', 'department', 'appointment', 'line_charts'));
            
            } else{
                //normal user 0
                return view('layouts.admin_layout');    
            }
    });

});


//user verification route
Route::get('/user/verify/{token}' , 'Auth\RegisterController@verifyUser')->middleware('auth');
Route::get('/resend/{id}' , 'Auth\RegisterController@resend')->middleware('auth');

Route::get('/hospital/departments', 'HospitalController@show_departments')->middleware('auth');
Route::get('/hospital/doctors' , 'HospitalController@show_doctors')->middleware('auth');

Route::get('/hospital/departments/{id}' , 'HospitalController@show_hospital_departments')->middleware('auth');
Route::resource('/hospitals', "HospitalController")->middleware('auth');

Route::resource('/doctors', "DoctorController")->middleware('auth');

Route::get('/doctors/hospitals/{id}' , 'DoctorController@show_all')->middleware('auth');

Route::get('/hospital/departments/doctors/{id}' , 'HospitalController@show_hospital_departments_doctors')->middleware('auth');
Route::get('/hospital/doctors/appointment/{id}' , 'AppointmentController@show_appointment')->middleware('auth');
Route::get('/appointments/hospitals/{id}' , 'AppointmentController@show_all')->middleware('auth');
Route::resource('/appointments', "AppointmentController")->middleware('auth');
// Route::get('/appointments//doctors')

Route::resource('/users', "UserController")->middleware('auth');

Route::get('/test' , function(){
    return view('queries.index');
});

Route::resource('/medicines', "MedicineController")->middleware('auth');

//list of user for super admin
Route::resource('user_details', "UserController")->middleware('auth');

//user profile detail
Route::resource('/profile', "UserDetailController")->middleware('auth');

//for storing answe
Route::post('/discussion/answer' , 'QueryController@store_answer')->middleware('auth');
Route::resource('/discussion', "QueryController")->middleware('auth');

Route::resource('/departments' , "DepartmentController")->middleware('auth');

Route::resource('/firstaids', "FirstaidController")->middleware('auth');
// Route::get('/firstaids/details' , 'FirstaidController@details');

Route::resource('/emergency_contact', "EmergencyController")->middleware('auth');

Route::resource('/schedule' , 'ScheduleController')->middleware('auth');
//for shifts
Route::post('/shifts' , 'ScheduleController@show_schedule')->middleware('auth');


Route::get('/check' , function(){
    $hospitals = App\Hospital::all();
    return view('doctors.set_schedule' , compact('hospitals'))->middleware('auth');
});

Route::get('/test/{token}', 'Api\RegisterController@sendAppointmentNotification')->middleware('auth');

Auth::routes();

Route::get('/details/{id}' , 'DoctorController@show_details')->middleware('auth');

Route::get('/appointment/details/{id}' , 'AppointmentController@appointment_show_details')->middleware('auth');

Route::post('/specific/appointments' , 'AppointmentController@specific_appointments')->middleware('auth');

Route::get('/doctor/schedule/details' , 'ScheduleController@doctor_schedule_details')->middleware('auth');

Route::get('/notification' , 'HomeController@notification')->middleware('auth');

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;


class User extends Authenticatable
{
    use HasApiTokens, Notifiable;
    

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
       'id', 'name', 'email', 'password', 'phone_number' , 'admin' , 'hospital_id','verified' ,'f_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function hospital(){
        return $this->belongsTo('App\Hospital');
    }
    
    public function verify_user()
    {
        return $this->hasOne('App\VerifyUser');
    }

    public function user_detail(){
        return $this->hasOne('App\User_Detail');
    }

    public function medicines(){
        return $this->hasMany('App\Medicine');
    }

   
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Mail\VerifyDoctor;
use Illuminate\Support\Facades\Mail;
use App\Hospital;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(Auth::user()->admin == 2){
            $users = User::where('id' , Auth::user()->id)->get();
        }else
        {
            $users = User::with('user_detail')->get();  
        }

    
            if($request->wantsJson())
            {
                return response()->json([
                    "status"=> 'success',
                    "message"=> 'All Users List',
                    "data"=> $users
                ]);
            }
            return view('users.index', compact('users'));

   
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $hospitals = Hospital::all();
        return view('users.create' , compact('hospitals'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       if($request['admin'] == 3){
        $raw_password=str_random(9);
        $request['password']= bcrypt($raw_password);
       }else{
        $request['password']=bcrypt($request->password);
       }

       $request['verified']= true;
        
        $add_new=User::create($request->all());

        $add_new['raw_password']= $raw_password;

        Mail::to($add_new->email)->send(new VerifyDoctor($add_new));

        return redirect('/users'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
            $hospitals=Hospital::all();
            $user= User::find($id);
            return view('users.edit' , compact('user', 'hospitals'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $old_user=User::find($id);
        $new_user=$request->all();
        $old_user->fill($new_user)->save();
        return redirect ('/users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=User::find($id);
        $user->delete();
        return redirect('/users');
    }
}

resources/views/users/create.blade.php
@extends('layouts.admin_layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add New</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="/users">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                         <div class="form-group{{ $errors->has('phone_number') ? ' has-error' : '' }}">
                            <label for="phone_number" class="col-md-4 control-label">phone_number</label>

                            <div class="col-md-6">
                                <input id="phone_number" type="text" class="form-control" name="phone_number" value="{{ old('phone_number') }}" required autofocus>

                                @if ($errors->has('phone_number'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone_number') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('admin') ? ' has-error' : '' }}">
                            <label for="admin" class="col-md-4 control-label">Role</label>

                            <div class="col-md-6">
                                <select name="admin" id="" class="form-control">
                                    <option value="0">User</option>
                                    <option value="1">Super Admin</option>
                                    <option value="2">Admin</option>
                                    <option value="3">Doctor</option>
                                </select>

                                @if ($errors->has('admin'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('admin') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                            <div class="form-group{{ $errors->has('hospital_id') ? ' has-error' : '' }}">
                                <label for="hospital_id" class="col-md-4 control-label">Hospital</label>

                                <div class="col-md-6">
                                    <select name="hospital_id" id="" class="form-control">
                                        <option disabled selected value>Select doctor</option>
                                        @foreach($hospitals as $hospital)
                                            <option value="{{$hospital->id}}">{{$hospital->name}}</option>
                                        @endforeach 
                                    
                                    </select>

                                    @if ($errors->has('hospital_id'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('hospital_id') }}</strong>
                                        </span>
                                    @endif
                                 </div>
                                
                            </div>
                      


                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.admin_layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="/users/{{$user->id}}">
                        {{ csrf_field() }}
                        {{method_field('PUT')}}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{$user->name}}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{$user->email}}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        @if (Auth::user()->admin==0)
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" value="{{$user->password}}" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        @endif
                        

                         <div class="form-group{{ $errors->has('phone_number') ? ' has-error' : '' }}">
                            <label for="phone_number" class="col-md-4 control-label">phone_number</label>

                            <div class="col-md-6">
                                <input id="phone_number" type="text" class="form-control" name="phone_number" value="{{$user->phone_number}}" required autofocus>

                                @if ($errors->has('phone_number'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone_number') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                       
                        
                        <div class="form-group {{ $errors->has('admin') ? ' has-error' : '' }} @if(Auth::user()->admin == 2) hidden @endif">
                            <label for="admin" class="col-md-4 control-label ">Role</label>

                            <div class="col-md-6">
                                <select name="admin" id="" class="form-control">
                                    <option value="0">User</option>
                                    <option value="1">Super Admin</option>
                                    <option value="2">Admin</option>
                                    <option value="3">Doctor</option>
                                </select>

                                @if ($errors->has('admin'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('admin') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                         <div class="form-group{{ $errors->has('hospital_id') ? ' has-error' : '' }}">
                                <label for="hospital_id" class="col-md-4 control-label">Role</label>

                                <div class="col-md-6">
                                    <select name="hospital_id" id="" class="form-control">
                                        @foreach($hospitals as $hospital)
                                            <option value="{{$hospital->id}}">{{$hospital->name}}</option>
                                        @endforeach 
                                    
                                    </select>

                                    @if ($errors->has('hospital_id'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('hospital_id') }}</strong>
                                        </span>
                                    @endif
                                 </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.admin_layout')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Users
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">User List</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Users List</h3>
                        <small style="margin-left: 15px">
                            <a href={{route('users.create')  }}>
                            @if(Auth::user()->admin == 1 )
                                <button type="submit" class="btn btn-success">Add New</button>
                            @endif 
                            </a>
                        </small>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive">
                       
                        <table id="example2" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>S.N.</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Phone Number</th>
                                <th>Role</th>
                                <th>Action</th>
                             </tr>
                            </thead>
                            <tbody>

                           @php($i=1)
                                @foreach($users as $user)
                                    <tr>
                                        <td>{{$i}}</td>
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>{{$user->phone_number}}</td>
                                        <td>
                                            @if($user->admin == 1)
                                                <span class="label label-success">Super Admin</span>
                                            @elseif($user->admin == 2)
                                                <span class="label label-primary">Admin</span>
                                            @elseif($user->admin == 3)
                                            <span class="label label-danger">Doctor</span>
                                            @else
                                            <span class="label label-info">User</span>
                                            @endif
                                        </td>
                                       
                                        <td>
                                            <div class="btn-group">

                                               
                                                <a href={{route('users.edit' ,  ['user' =>$user->id])  }}>
                                                    <button type="submit" class="btn btn-primary">Edit</button>
                                                </a>
                                                <form  method="POST"
                                                      style="display: inline" action={{route('users.destroy' ,['user'=>$user->id])}} >
                                                    {{csrf_field()}}
                                                    {{method_field("DELETE")}}
                                                    <button type="submit" class="btn btn-danger"
                                                            onclick="return confirm('Are you sure you want to delete?')">
                                                          
                                                        Delete
                                                    </button>
                                                </form>

                                            </div>
                                        </td>
                                    </tr>
                                    @php($i++)
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.content -->

@endsection