routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['middleware' => ['web','auth']], function(){
    

    Route::get('/', function(){
        //super-admin=1 admin=2 doctor=3 
        if(Auth::user()->admin ==1 || Auth::user()->admin == 3 ){
            $doctor = \App\Doctor::all()->count();
            // $department = \App\Department::all()->count();

            $line_charts_array = array();
            for($i = 1 ; $i<=8 ; $i++){
                $date = \Carbon\Carbon::now()->addDays($i);
                $appointment_count= \App\Appointment::where('date', $date->format('Y-m-d'))->count();
                $line_chart['period'] = $date->format('Y-m-d');
                $line_chart['appointments'] = $appointment_count;
                array_push($line_charts_array , $line_chart);

            }

        $line_charts = json_encode($line_charts_array);
                return view('home' , compact('doctor' , 'line_charts'));
        }
        elseif (Auth::user()->admin == 2 ) {
            $users['users']= \App\User::all();
            $doctor = \App\Doctor::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $department = \App\Department::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $appointment = \App\Appointment::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $firstaid =\App\Firstaid::all()->count();
            
            $line_charts_array = array();
                for($i = 1 ; $i<=8 ; $i++){
                    $date = \Carbon\Carbon::now()->addDays($i);
                    $appointment_count= \App\Appointment::where('hospital_id', Auth::user()->hospital_id)->where('date', $date->format('Y-m-d'))->count();
                    $line_chart['period'] = $date->format('Y-m-d');
                    $line_chart['appointments'] = $appointment_count;
                    array_push($line_charts_array , $line_chart);

                }

            $line_charts = json_encode($line_charts_array);
      

                return view('home', compact('users' , 'doctor' , 'firstaid', 'department', 'appointment', 'line_charts'));
            
            } else{
                //normal user 0
                return view('layouts.admin_layout');    
            }
    });

});


//user verification route
Route::get('/user/verify/{token}' , 'Auth\RegisterController@verifyUser')->middleware('auth');
Route::get('/resend/{id}' , 'Auth\RegisterController@resend')->middleware('auth');

Route::get('/hospital/departments', 'HospitalController@show_departments')->middleware('auth');
Route::get('/hospital/doctors' , 'HospitalController@show_doctors')->middleware('auth');

Route::get('/hospital/departments/{id}' , 'HospitalController@show_hospital_departments')->middleware('auth');
Route::resource('/hospitals', "HospitalController")->middleware('auth');

Route::resource('/doctors', "DoctorController")->middleware('auth');

Route::get('/doctors/hospitals/{id}' , 'DoctorController@show_all')->middleware('auth');

Route::get('/hospital/departments/doctors/{id}' , 'HospitalController@show_hospital_departments_doctors')->middleware('auth');
Route::get('/hospital/doctors/appointment/{id}' , 'AppointmentController@show_appointment')->middleware('auth');
Route::get('/appointments/hospitals/{id}' , 'AppointmentController@show_all')->middleware('auth');
Route::resource('/appointments', "AppointmentController")->middleware('auth');
// Route::get('/appointments//doctors')

Route::resource('/users', "UserController")->middleware('auth');

Route::get('/test' , function(){
    return view('queries.index');
});

Route::resource('/medicines', "MedicineController")->middleware('auth');

//list of user for super admin
Route::resource('user_details', "UserController")->middleware('auth');

//user profile detail
Route::resource('/profile', "UserDetailController")->middleware('auth');

//for storing answe
Route::post('/discussion/answer' , 'QueryController@store_answer')->middleware('auth');
Route::resource('/discussion', "QueryController")->middleware('auth');

Route::resource('/departments' , "DepartmentController")->middleware('auth');

Route::resource('/firstaids', "FirstaidController")->middleware('auth');
// Route::get('/firstaids/details' , 'FirstaidController@details');

Route::resource('/emergency_contact', "EmergencyController")->middleware('auth');

Route::resource('/schedule' , 'ScheduleController')->middleware('auth');
//for shifts
Route::post('/shifts' , 'ScheduleController@show_schedule')->middleware('auth');


Route::get('/check' , function(){
    $hospitals = App\Hospital::all();
    return view('doctors.set_schedule' , compact('hospitals'))->middleware('auth');
});

Route::get('/test/{token}', 'Api\RegisterController@sendAppointmentNotification')->middleware('auth');

Auth::routes();

Route::get('/details/{id}' , 'DoctorController@show_details')->middleware('auth');

Route::get('/appointment/details/{id}' , 'AppointmentController@appointment_show_details')->middleware('auth');

Route::post('/specific/appointments' , 'AppointmentController@specific_appointments')->middleware('auth');

Route::get('/doctor/schedule/details' , 'ScheduleController@doctor_schedule_details')->middleware('auth');

Route::get('/notification' , 'HomeController@notification')->middleware('auth');

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    protected $fillable=['name','address','contact_no','nmc_no' , 'hospital_id' , 'department_id'];

    public function appointments(){
        return $this->hasMany('App\Appointment');
    }

    public function hospital(){
        return $this->belongsTo('App\Hospital');
    }

    public function department(){
        return $this->belongsTo('App\Department');
    }
    
}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Doctor;
use Illuminate\Support\Facades\Auth;
use App\Department;
use App\Doctor_Hospital;
use App\User;
use App\Doctor_Schedule;
use App\Hospital;
use Carbon\Carbon;


class DoctorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
   
        if(Auth::user()->admin == 2){
            $doctors = Doctor::where('hospital_id' , Auth::user()->hospital->id)->get();
        
        }else{
            $doctors = doctor::all();
        }

        if($request->wantsJson()){
            return response()->json([
                'status' => 'success',
                'message' => 'doctort list',
                'data' => $doctors
            ]); 
        }

        return view('doctors.index' ,compact('doctors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $hospital_id=Auth::user()->hospital_id;
        $departments=Department::where('hospital_id' , $hospital_id)->get();
        $doctors = User::where('admin' , 3)->get();
        return view('doctors.create', compact('departments' , 'doctors'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      $add_new_doctor=Doctor::create($request->all());
      
        return redirect('/doctors'); 

        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $doctor= Doctor::find($id);
        return view('doctors.edit' , compact('doctor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $old_doctor= Doctor::find($id);
        $new_doctor= $request->all();
        $old_doctor->fill($new_doctor)->save();
        return redirect ('/doctors'); 

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $doctor=Doctor::find($id);
        $doctor->delete();
        return redirect('/doctors');
    }

    public function show_all($id){
        $doctors = Doctor::where('id' , $id)->get();

        return view('doctors.index' ,compact('doctors'));
    }

    public function show_details(Request $request , $id){
        
        $doctor = Doctor::find($id);
        
        $hospital = Hospital::where('id' , $doctor->hospital_id)->first();

        $department = Department::where('id' , $doctor->department_id)->first();
       

        if($request->wantsJson()){
            return response()->json([
                'status' => 'success',
                'message' => 'Details list',
                'data' => ['doctor' => $doctor , 'hospital'=> $hospital , 'department' => $department]
            ]);
        }

    }


    public function appointments_all(Request $request){
            $doctors = Doctor::all();
            $hospitals = Hospital::all();
            $departments = Department::all();
            $shifts = Doctor_Schedule::all();
        
            $schedules = array();

            foreach($shifts as $shift){
                if(!empty($shift->from) ){
                    $from = Carbon::parse($shift->from)->format('H:i:s');
                    $to = Carbon::parse($shift->to)->format('H:i:s');
                   
                    $current_date_time = Carbon::now();
 
                    $current_time = $current_date_time->format('H:i:s');
                    $current_date = $current_date_time->format('Y-m-d');

                   

                    if(!empty($from) && !empty($to)){
                        
                        if($shift->date >= $current_date ){
                           array_push($schedules , $shift);
                        }
                    }
                        
                    
                }
                
            }

            // && $from >= $current_time

            if($request->wantsJson()){
                return response()->json([
                    'status' => 'success',
                    'message' => 'Details list',
                    'data' => ['doctors' => $doctors , 'hospitals'=> $hospitals , 'departments' => $departments,'schedules'=>$schedules]
                ]);
            }
    }

}

resources/views/doctors/create.blade.php
@extends('layouts.admin_layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add New</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="/doctors">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Doctor Name</label>

                            <div class="col-md-6">
                            <select name="name" id="" class="form-control">
                                        @foreach($doctors as $doctor)
                                            <option value="{{$doctor->name}}">{{$doctor->name}}</option>
                                        @endforeach
                                    </select>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                         <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label for="address" class="col-md-4 control-label">Address</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control" name="address" value="{{ old('address') }}" required autofocus>

                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                           <div class="form-group{{ $errors->has('contact_no') ? ' has-error' : '' }}">
                            <label for="contact_no" class="col-md-4 control-label">Phone Number</label>

                            <div class="col-md-6">
                                <input id="contact_no" type="text" class="form-control" name="contact_no" value="{{ old('contact_no') }}" required autofocus>

                                @if ($errors->has('contact_no'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('contact_no') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                           <div class="form-group{{ $errors->has('nmc_no') ? ' has-error' : '' }}">
                            <label for="nmc_no" class="col-md-4 control-label">Nmc No</label>

                            <div class="col-md-6">
                                <input id="nmc_no" type="text" class="form-control" name="nmc_no" value="{{ old('nmc_no') }}" required autofocus>

                                @if ($errors->has('nmc_no'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nmc_no') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('department_id') ? ' has-error' : '' }}">
                            <label for="department_id" class="col-md-4 control-label">Department Name</label>

                            <div class="col-md-6">
                                    <select name="department_id" id="" class="form-control">
                                        @foreach($departments as $department)
                                            <option value="{{$department->id}}">{{$department->name}}</option>
                                        @endforeach
                                    </select>
                                @if ($errors->has('department_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('department_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <input type="hidden" name="hospital_id" value={{Auth::user()->hospital_id}}>
                        


                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/doctors/edit.blade.php
@extends('layouts.admin_layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="/doctors/{{$doctor->id}}">
                        {{ csrf_field() }}
                        {{method_field('PUT')}}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Doctor Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{$doctor->name}}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                         <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label for="address" class="col-md-4 control-label">Address</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control" name="address" value="{{$doctor->address}}" required autofocus>

                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                           <div class="form-group{{ $errors->has('contact_no') ? ' has-error' : '' }}">
                            <label for="contact_no" class="col-md-4 control-label">Phone Number</label>

                            <div class="col-md-6">
                                <input id="contact_no" type="text" class="form-control" name="contact_no" value="{{$doctor->contact_no}}" required autofocus>

                                @if ($errors->has('contact_no'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('contact_no') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                           <div class="form-group{{ $errors->has('nmc_no') ? ' has-error' : '' }}">
                            <label for="nmc_no" class="col-md-4 control-label">Nmc No</label>

                            <div class="col-md-6">
                                <input id="nmc_no" type="text" class="form-control" name="nmc_no" value="{{$doctor->contact_no}}" required autofocus>

                                @if ($errors->has('nmc_no'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nmc_no') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/doctors/index.blade.php
@extends('layouts.admin_layout')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Doctors
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Doctor List</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Doctors List</h3>
                        <small style="margin-left: 15px">
                        @if(Auth::user()->admin==1 || Auth::user()->admin==2)
                            <a href={{route('doctors.create')  }}>
                                <button type="submit" class="btn btn-success">Add New</button>
                            </a>
                            @endif
                        </small>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive">
                       
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>S.N.</th>
                                <th>Doctors name</th>
                                <th>Address</th>
                                <th>Phone Number</th>
                                <th>Department</th>
                                <th>Nmc No.</th>
                           </tr>
                            </thead>
                            <tbody>

                           @php($i=1)
                                @foreach($doctors as $doctor)
                                    <tr>
                                        <td>{{$i}}</td>
                                        <td>{{$doctor->name}}</td>
                                        <td>{{$doctor->address}}</td>
                                        <td>{{$doctor->contact_no}}</td>
                                        <td>{{$doctor->department->name}}</td>
                                        <td>{{$doctor->nmc_no}}</td>
                                       
                                        <td>
                                            <div class="btn-group">
                                               @if (Auth::user()->admin==1 || Auth::user()->admin==2)
                                                <a href={{route('doctors.edit' ,  ['doctor' =>$doctor->id])  }}>
                                                    <button type="submit" class="btn btn-primary">Edit</button>
                                                </a>
                                                <form action={{route('doctors.destroy' ,['doctor'=>$doctor->id])}} method="POST"
                                                      style="display: inline">
                                                    {{csrf_field()}}
                                                    {{method_field("DELETE")}}
                                                    <button type="submit" class="btn btn-danger"
                                                            onclick="return confirm('Are you sure you want to delete?')">
                                                          
                                                        Delete
                                                    </button>
                                                </form>
                                            @endif
                                            </div>

                                              <div class="btn-group">
                                               @if ( Auth::user()->admin==0)
                                                 <a href={{url('/hospital/doctors/appointment/'.$doctor->id) }}>
                                                   <button type="submit" class="btn btn-success">Make Appointment</button>
                                                 </a>
                                               
                                               @endif
                                               </div>
                                        </td>
                                    </tr>
                                    @php($i++)
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.content -->

@endsection

resources/views/doctors/index_schedule.blade.php
@extends('layouts.admin_layout')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Doctors
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Schedule  List</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Doctors List</h3>
                        <small style="margin-left: 15px">
                        @if(Auth::user()->admin==3)
                            <a href={{route('schedule.create')  }}>
                                <button type="submit" class="btn btn-success">Add New</button>
                            </a>
                            @endif
                        </small>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive">
                       
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>S.N.</th>
                                <th>Hospitals name</th>
                                <th>Date</th>
                                <th colspan="2">Morning Shift</th>
                                <th colspan="2">Day Shift</th>
                                <th colspan="2">Evening Shift</th>
                           </tr>
                            </thead>
                            <tbody>

                           @php($i=1)
                               
                                    <tr>
                                        <td>{{$i}}</td>
                                        <td>haha</td>
                                        <td>hehe</td>
                                        <th>From</th>
                                        <th>To</th>
                                        <th>From</th>
                                        <th>To</th>
                                        <th>From</th>
                                        <th>To</th>
                                        <td>
                                        <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>aw</td>
                                        <td>aws</td>
                                        </tr>
                                            <!-- <div class="btn-group">
                                               @if (Auth::user()->admin==1 || Auth::user()->admin==2)
                                                <a href={{route('doctors.edit' ,  ['doctor' =>$doctor->id])  }}>
                                                    <button type="submit" class="btn btn-primary">Edit</button>
                                                </a>
                                                <form action={{route('doctors.destroy' ,['doctor'=>$doctor->id])}} method="POST"
                                                      style="display: inline">
                                                    {{csrf_field()}}
                                                    {{method_field("DELETE")}}
                                                    <button type="submit" class="btn btn-danger"
                                                            onclick="return confirm('Are you sure you want to delete?')">
                                                          
                                                        Delete
                                                    </button>
                                                </form>
                                            @endif
                                            </div> -->

                                              <!-- <div class="btn-group"> -->
                                               @if ( Auth::user()->admin==0)
                                                 <a href={{url('/hospital/doctors/appointment/'.$doctor->id) }}>
                                                   <button type="submit" class="btn btn-success">Make Appointment</button>
                                                 </a>
                                               
                                               @endif
                                               </div>
                                        </td>
                                    </tr>
                                   
                                    @php($i++)
                               
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.content -->

@endsection