routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['middleware' => ['web','auth']], function(){
    

    Route::get('/', function(){
        //super-admin=1 admin=2 doctor=3 
        if(Auth::user()->admin ==1 || Auth::user()->admin == 3 ){
            $doctor = \App\Doctor::all()->count();
            // $department = \App\Department::all()->count();

            $line_charts_array = array();
            for($i = 1 ; $i<=8 ; $i++){
                $date = \Carbon\Carbon::now()->addDays($i);
                $appointment_count= \App\Appointment::where('date', $date->format('Y-m-d'))->count();
                $line_chart['period'] = $date->format('Y-m-d');
                $line_chart['appointments'] = $appointment_count;
                array_push($line_charts_array , $line_chart);

            }

        $line_charts = json_encode($line_charts_array);
                return view('home' , compact('doctor' , 'line_charts'));
        }
        elseif (Auth::user()->admin == 2 ) {
            $users['users']= \App\User::all();
            $doctor = \App\Doctor::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $department = \App\Department::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $appointment = \App\Appointment::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $firstaid =\App\Firstaid::all()->count();
            
            $line_charts_array = array();
                for($i = 1 ; $i<=8 ; $i++){
                    $date = \Carbon\Carbon::now()->addDays($i);
                    $appointment_count= \App\Appointment::where('hospital_id', Auth::user()->hospital_id)->where('date', $date->format('Y-m-d'))->count();
                    $line_chart['period'] = $date->format('Y-m-d');
                    $line_chart['appointments'] = $appointment_count;
                    array_push($line_charts_array , $line_chart);

                }

            $line_charts = json_encode($line_charts_array);
      

                return view('home', compact('users' , 'doctor' , 'firstaid', 'department', 'appointment', 'line_charts'));
            
            } else{
                //normal user 0
                return view('layouts.admin_layout');    
            }
    });

});


//user verification route
Route::get('/user/verify/{token}' , 'Auth\RegisterController@verifyUser')->middleware('auth');
Route::get('/resend/{id}' , 'Auth\RegisterController@resend')->middleware('auth');

Route::get('/hospital/departments', 'HospitalController@show_departments')->middleware('auth');
Route::get('/hospital/doctors' , 'HospitalController@show_doctors')->middleware('auth');

Route::get('/hospital/departments/{id}' , 'HospitalController@show_hospital_departments')->middleware('auth');
Route::resource('/hospitals', "HospitalController")->middleware('auth');

Route::resource('/doctors', "DoctorController")->middleware('auth');

Route::get('/doctors/hospitals/{id}' , 'DoctorController@show_all')->middleware('auth');

Route::get('/hospital/departments/doctors/{id}' , 'HospitalController@show_hospital_departments_doctors')->middleware('auth');
Route::get('/hospital/doctors/appointment/{id}' , 'AppointmentController@show_appointment')->middleware('auth');
Route::get('/appointments/hospitals/{id}' , 'AppointmentController@show_all')->middleware('auth');
Route::resource('/appointments', "AppointmentController")->middleware('auth');
// Route::get('/appointments//doctors')

Route::resource('/users', "UserController")->middleware('auth');

Route::get('/test' , function(){
    return view('queries.index');
});

Route::resource('/medicines', "MedicineController")->middleware('auth');

//list of user for super admin
Route::resource('user_details', "UserController")->middleware('auth');

//user profile detail
Route::resource('/profile', "UserDetailController")->middleware('auth');

//for storing answe
Route::post('/discussion/answer' , 'QueryController@store_answer')->middleware('auth');
Route::resource('/discussion', "QueryController")->middleware('auth');

Route::resource('/departments' , "DepartmentController")->middleware('auth');

Route::resource('/firstaids', "FirstaidController")->middleware('auth');
// Route::get('/firstaids/details' , 'FirstaidController@details');

Route::resource('/emergency_contact', "EmergencyController")->middleware('auth');

Route::resource('/schedule' , 'ScheduleController')->middleware('auth');
//for shifts
Route::post('/shifts' , 'ScheduleController@show_schedule')->middleware('auth');


Route::get('/check' , function(){
    $hospitals = App\Hospital::all();
    return view('doctors.set_schedule' , compact('hospitals'))->middleware('auth');
});

Route::get('/test/{token}', 'Api\RegisterController@sendAppointmentNotification')->middleware('auth');

Auth::routes();

Route::get('/details/{id}' , 'DoctorController@show_details')->middleware('auth');

Route::get('/appointment/details/{id}' , 'AppointmentController@appointment_show_details')->middleware('auth');

Route::post('/specific/appointments' , 'AppointmentController@specific_appointments')->middleware('auth');

Route::get('/doctor/schedule/details' , 'ScheduleController@doctor_schedule_details')->middleware('auth');

Route::get('/notification' , 'HomeController@notification')->middleware('auth');

app/Medicine.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Medicine extends Model
{
    protected $fillable=['name'];

    public function schedules(){
        return $this->hasMany('App\Medicine_Schedule');
    }
}

app/Http/Controllers/MedicineController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Medicine;
use App\Medicine_Schedule;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use App\User;

class MedicineController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $medicines = Medicine::with('schedules')->get();


        if($request->wantsJson()){
            return response()->json([
                'status' => 'success',
                'message' => 'Medicines list',
                'data' => $medicines
            ]); 
        }

        return view('medicines.index' ,compact('medicines'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('medicines.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $request['start_date']=Carbon::createFromFormat('m/d/Y' , $request->start_date);
        // $request['end_date']=Carbon::createFromFormat('m/d/Y' , $request->end_date);
        
        $medicine = new Medicine();
        $medicine->name = $request->input('name');
        $medicine->user_id=$request['user_id'];
        $medicine->start_date=$request->start_date;
        $medicine->end_date=$request->end_date;    
        $medicine->save();


       
        $schedules = array();
        if(!empty($request['time1'])){
            $schedule = new Medicine_Schedule();
            $schedule->medicine_id = $medicine->id;
            // $new_time = Carbon::createFromFormat('H:i a' , $single_time);
            $schedule->time = $request['time1'];
            $schedule->save();
            array_push($schedules , $schedule);
        }

        if(!empty($request['time2'])){
            $schedule = new Medicine_Schedule();
            $schedule->medicine_id = $medicine->id;
            // $new_time = Carbon::createFromFormat('H:i a' , $single_time);
            $schedule->time = $request['time2'];
            $schedule->save();
            array_push($schedules , $schedule);
        }
        if(!empty($request['time3'])){
            $schedule = new Medicine_Schedule();
            $schedule->medicine_id = $medicine->id;
            // $new_time = Carbon::createFromFormat('H:i a' , $single_time);
            $schedule->time = $request['time3'];
            $schedule->save();
            array_push($schedules , $schedule);
        }

        if(!empty($request['time4'])){
            $schedule = new Medicine_Schedule();
            $schedule->medicine_id = $medicine->id;
            // $new_time = Carbon::createFromFormat('H:i a' , $single_time);
            $schedule->time = $request['time4'];
            $schedule->save();
            array_push($schedules , $schedule);
        }
        // foreach($request['time'] as $single_time){
            

        //     $schedule = new Medicine_Schedule();
        //     $schedule->medicine_id = $medicine->id;
        //     // $new_time = Carbon::createFromFormat('H:i a' , $single_time);
        //     $schedule->time = $single_time;
        //     $schedule->save();
        // }  
        
    
        if($request->wantsJson()){
            return response()->json([
                'status' => 'success',
                'message' => 'Medicine store successfully',
                'data' => [$medicine , $schedules]
            ]); 
        }

        return redirect('/medicines'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $medicine=Medicine::find($id);

        if($request->wantsJson()){
            return response()->json([
                'status' => 'success',
                'message' => 'respective medicines details',
                'data' => $medicine
            ]); 
        }
        return view('medicines.edit', compact('medicine'));
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $medicine_schedule=Medicine_Schedule::find($id);
        $medicine_schedule->delete();
        return redirect('/medicines');
    
    }

    //users' medicines
    public function user_medicine(Request $request){
        $user = User::findorfail($request['user_id']);

        $medicine = $user->medicines;

        if($request->wantsJson()){
            return response()->json([
                'status' => 'success',
                'message' => 'Users medicines',
                'data' => $medicine
            ]);
        }
    }


    //users' medicines time 
    public function medicine_time(Request $request){

        $medicine = Medicine::findorfail($request['medicine_id']);

        $time = $medicine->schedules;

        if($request->wantsJson()){
            return response()->json([
                'status' => 'success',
                'message' => 'Medicine respective time',
                'data' => $time
            ]);
        }
    }
}

resources/views/medicines/create.blade.php
@extends('layouts.admin_layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add medicine Schedule</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="/medicines">
                        {{ csrf_field() }}
                       
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Medicine Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        

                        

                        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">Start Date</label>

                            <div class="col-md-6">
                                <input id="start_date" type="text" class="form-control datepicker" name="start_date" value="{{ old('start_date') }}" required autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                         <div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                            <label for="end_date" class="col-md-4 control-label">End Date</label>

                            <div class="col-md-6">
                                <input id="end_date" type="text" class="form-control datepicker" name="end_date" value="{{ old('end_date') }}" required autofocus>

                                @if ($errors->has('end_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('end_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('time') ? ' has-error' : '' }}">
                            <label for="time" class="col-md-4 control-label">Time</label>

                            <div class="col-md-6 bootstrap-timepicker" id="add-time" >
                                <input id="time" type="text" class="form-control timepicker" style="margin-bottom:10px" name="time[]" value="{{ old('time') }}" required >

                            

                                

                                @if ($errors->has('time'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('time') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-2">
                                <button type="button"  class="form-control btn btn-success btn-sm" id="add" >Add</button>
                                <button type="button" class='form-control btn btn-danger btn-sm' id="remove" >Remove</button>
                            </div>


                        </div>


                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                        Add medicine
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $('body').on('click' , '#add' , function(){
            $("#add-time").append('<input id="time" type="text" class="form-control timepicker" style="margin-bottom:10px" name="time[]" value="{{ old('time') }}" required >');
            
            $('.timepicker').timepicker({
            showInputs: false,
            defaultTime: false
        });
        });

        $('body').on('click' , '#remove' , function(){
            var count = $('#add-time input').length;
            if(count > 1 ){
                $('#add-time input:last-child').remove();
            }
        });
    </script>
@endsection

resources/views/medicines/edit.blade.php
@extends('layouts.admin_layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add medicine Schedule</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="/medicines/{{$medicine->id}}">
                        {{ csrf_field() }}
                        {{method_field('PUT')}}


                        <div class="form-group{{ $errors->has('time') ? ' has-error' : '' }}">
                            <label for="time" class="col-md-4 control-label">Time</label>

                            <div class="col-md-6 bootstrap-timepicker" >
                                <input id="time" type="text" class="form-control timepicker" name="time" value="{{$medicine->time}}" required >

                                @if ($errors->has(''))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('time') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">Start Date</label>

                            <div class="col-md-6">
                                <input id="start_date" type="text" class="form-control datepicker" name="start_date" value="{{$medicine->start_date}}" required autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                            <label for="end_date" class="col-md-4 control-label">Start Date</label>

                            <div class="col-md-6">
                                <input id="end_date" type="text" class="form-control datepicker" name="end_date" value="{{$medicine->end_date}}" required autofocus>

                                @if ($errors->has('end_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('end_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Book medicine
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/medicines/index.blade.php
@extends('layouts.admin_layout')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Medicine Schedule
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Medicine Schedule</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="box">
                    <div class="box-header">
                        
                        <small style="margin-left: 15px">
                       
                            <a href={{route('medicines.create')  }}>
                                <button type="submit" class="btn btn-success">Add Medicine</button>
                            </a>
                            
                        </small>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive">
                       
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>S.N.</th>
                                <th>Medicine Name</th>
                                <th>Time</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                           </tr>
                            </thead>
                            <tbody>

                           @php($i=1)
                                @foreach($medicines as $medicine)
                                <tr>
                                    @foreach($medicine->schedules as $medicine_schedule)

                                        <td>{{$i}}</td>                                       
                                        <td>{{$medicine->name}}</td>
                                        <td>{{$medicine_schedule->time}}</td>
                                        <td>{{$medicine->start_date}}</td>
                                        <td>{{$medicine->end_date}}</td>
                                  
                                        <td>
                                            <div class="btn-group">
                                               @if(Auth::user()->admin==0)
                                                <a href={{route('medicines.edit' ,  ['medicine' =>$medicine->id])  }}>
                                                    <button type="submit" class="btn btn-primary">Edit</button>
                                                </a>
                                                <form action={{route('medicines.destroy' ,['medicine'=>$medicine_schedule->id])}} method="POST"
                                                      style="display: inline">
                                                    {{csrf_field()}}
                                                    {{method_field("DELETE")}}
                                                    <button type="submit" class="btn btn-danger"
                                                            onclick="return confirm('Are you sure you want to delete?')">
                                                          
                                                        Delete
                                                    </button>
                                                </form>
                                               
                                            @endif
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                    @php($i++)
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.content -->

@endsection