routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['middleware' => ['web','auth']], function(){
    

    Route::get('/', function(){
        //super-admin=1 admin=2 doctor=3 
        if(Auth::user()->admin ==1 || Auth::user()->admin == 3 ){
            $doctor = \App\Doctor::all()->count();
            // $department = \App\Department::all()->count();

            $line_charts_array = array();
            for($i = 1 ; $i<=8 ; $i++){
                $date = \Carbon\Carbon::now()->addDays($i);
                $appointment_count= \App\Appointment::where('date', $date->format('Y-m-d'))->count();
                $line_chart['period'] = $date->format('Y-m-d');
                $line_chart['appointments'] = $appointment_count;
                array_push($line_charts_array , $line_chart);

            }

        $line_charts = json_encode($line_charts_array);
                return view('home' , compact('doctor' , 'line_charts'));
        }
        elseif (Auth::user()->admin == 2 ) {
            $users['users']= \App\User::all();
            $doctor = \App\Doctor::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $department = \App\Department::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $appointment = \App\Appointment::where('hospital_id' , \Auth::user()->hospital_id)->count();
            $firstaid =\App\Firstaid::all()->count();
            
            $line_charts_array = array();
                for($i = 1 ; $i<=8 ; $i++){
                    $date = \Carbon\Carbon::now()->addDays($i);
                    $appointment_count= \App\Appointment::where('hospital_id', Auth::user()->hospital_id)->where('date', $date->format('Y-m-d'))->count();
                    $line_chart['period'] = $date->format('Y-m-d');
                    $line_chart['appointments'] = $appointment_count;
                    array_push($line_charts_array , $line_chart);

                }

            $line_charts = json_encode($line_charts_array);
      

                return view('home', compact('users' , 'doctor' , 'firstaid', 'department', 'appointment', 'line_charts'));
            
            } else{
                //normal user 0
                return view('layouts.admin_layout');    
            }
    });

});


//user verification route
Route::get('/user/verify/{token}' , 'Auth\RegisterController@verifyUser')->middleware('auth');
Route::get('/resend/{id}' , 'Auth\RegisterController@resend')->middleware('auth');

Route::get('/hospital/departments', 'HospitalController@show_departments')->middleware('auth');
Route::get('/hospital/doctors' , 'HospitalController@show_doctors')->middleware('auth');

Route::get('/hospital/departments/{id}' , 'HospitalController@show_hospital_departments')->middleware('auth');
Route::resource('/hospitals', "HospitalController")->middleware('auth');

Route::resource('/doctors', "DoctorController")->middleware('auth');

Route::get('/doctors/hospitals/{id}' , 'DoctorController@show_all')->middleware('auth');

Route::get('/hospital/departments/doctors/{id}' , 'HospitalController@show_hospital_departments_doctors')->middleware('auth');
Route::get('/hospital/doctors/appointment/{id}' , 'AppointmentController@show_appointment')->middleware('auth');
Route::get('/appointments/hospitals/{id}' , 'AppointmentController@show_all')->middleware('auth');
Route::resource('/appointments', "AppointmentController")->middleware('auth');
// Route::get('/appointments//doctors')

Route::resource('/users', "UserController")->middleware('auth');

Route::get('/test' , function(){
    return view('queries.index');
});

Route::resource('/medicines', "MedicineController")->middleware('auth');

//list of user for super admin
Route::resource('user_details', "UserController")->middleware('auth');

//user profile detail
Route::resource('/profile', "UserDetailController")->middleware('auth');

//for storing answe
Route::post('/discussion/answer' , 'QueryController@store_answer')->middleware('auth');
Route::resource('/discussion', "QueryController")->middleware('auth');

Route::resource('/departments' , "DepartmentController")->middleware('auth');

Route::resource('/firstaids', "FirstaidController")->middleware('auth');
// Route::get('/firstaids/details' , 'FirstaidController@details');

Route::resource('/emergency_contact', "EmergencyController")->middleware('auth');

Route::resource('/schedule' , 'ScheduleController')->middleware('auth');
//for shifts
Route::post('/shifts' , 'ScheduleController@show_schedule')->middleware('auth');


Route::get('/check' , function(){
    $hospitals = App\Hospital::all();
    return view('doctors.set_schedule' , compact('hospitals'))->middleware('auth');
});

Route::get('/test/{token}', 'Api\RegisterController@sendAppointmentNotification')->middleware('auth');

Auth::routes();

Route::get('/details/{id}' , 'DoctorController@show_details')->middleware('auth');

Route::get('/appointment/details/{id}' , 'AppointmentController@appointment_show_details')->middleware('auth');

Route::post('/specific/appointments' , 'AppointmentController@specific_appointments')->middleware('auth');

Route::get('/doctor/schedule/details' , 'ScheduleController@doctor_schedule_details')->middleware('auth');

Route::get('/notification' , 'HomeController@notification')->middleware('auth');

app/Firstaid.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Firstaid extends Model
{
    protected $fillable=['name'];

    public function details(){
        return $this->hasMany('App\FirstAidDescription');
    }
}

app/Http/Controllers/FirstaidController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Firstaid;
use App\FirstAidDescription;

class FirstaidController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //return firstaid with respective descriptions
        $firstaids = Firstaid::with('details')->get();        

        if($request->wantsJson()){
            return response()->json([
                'status' => 'success',
                'message' => 'Firstaid list',
                'data' => $firstaids
            ]); 
        }

        return view('firstaids.index' ,compact('firstaids'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('firstaids.create');
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $add_new=Firstaid::create($request->all());

        foreach($request['descriptions'] as $single_description){
            $new_description = new FirstAidDescription;
            $new_description->firstaid_id = $add_new->id;
            $new_description->descriptions = $single_description;
            $new_description->save();
        }


        return redirect('/firstaids');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request , $id)
    {
       $firstaid = Firstaid::find($id);

       if($request->wantsJson()){
        return response()->json([
            'status' => 'success',
            'message' => 'respective firstaid details',
            'data' => $firstaid
        ]); 
       }
       return view('firstaids.detail' , compact('firstaid')); 

 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/firstaids/create.blade.php
@extends('layouts.admin_layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add New</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="/firstaids">
                        {{ csrf_field() }}

                    

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">First Aid</label>

                            <div class="col-md-6">
                                <input id="name" type="name" class="form-control" name="name" value="{{ old('name') }}" required>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        
                        

                         <div class="form-group{{ $errors->has('descriptions') ? ' has-error' : '' }}">
                            <label for="details" class="col-md-4 control-label">Details</label>

                            <div class="col-md-6" id='details'>
                                <input id="descriptions" type="text" style="margin-bottom:10px" class="form-control" name="descriptions[]" value="{{ old('details') }}" required autofocus>
                                
                                @if ($errors->has('descriptions'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('descriptions') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-2">
                                <button type="button"  class="form-control btn btn-success btn-sm" id="add" >Add</button>
                                <button type="button" class='form-control btn btn-danger btn-sm' id="remove" >Remove</button>
                            </div>
                        </div>

                        
                            

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $('body').on('click' , '#add' , function(){
            $("#details").append('<input id="descriptions" type="text" style="margin-bottom:10px" class="form-control" name="descriptions[]" >');
        });

        $('body').on('click' , '#remove' , function(){
            var count = $('#details input').length;
            if(count > 1 ){
                $('#details input:last-child').remove();
            }
        });
    </script>
@endsection

resources/views/firstaids/detail.blade.php
@extends('layouts.admin_layout')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        {{$firstaid->name}}
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="box">
                    
                    <!-- /.box-header -->
                    <div class="box-body table-responsive">
                       
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>
                                {{$firstaid->name}}
                                </th>
                           </tr>
                           <tr>
                            <th>Details</th>
                           </tr>
                            </thead>
                            <tbody>

                        
                              
                                     
                            @foreach($firstaid->details as $single_details)
                                     <tr>
                                        <td>{{$single_details->descriptions}}</td>
                                    </tr>
                            @endforeach        
                                   
                             

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.content -->

@endsection

resources/views/firstaids/index.blade.php
@extends('layouts.admin_layout')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            First Aid
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">First Aid</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="box">
                    <div class="box-header">
                        
                        <small style="margin-left: 15px">
                        @if(Auth::user()->admin==1)
                            <a href={{route('firstaids.create')  }}>
                                <button type="submit" class="btn btn-success">Add Firstaid</button>
                            </a>
                           @endif 
                        </small>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive">
                       
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>S.N.</th>
                                <th>First Aids</th>
                                <th>Details</th>
                           </tr>
                            </thead>
                            <tbody>

                           @php($i=1)
                                @foreach($firstaids as $firstaid)
                                    <tr>
                                        <td>{{$i}}</td>                                       
                                        <td>{{$firstaid->name}}</td>
                                        <td><div class="btn-group"><a href={{route('firstaids.show', ['firstaid' => $firstaid->id])}}>
                                                    <button type="submit" class="btn btn-primary">View Details</button>
                                                </a>
                                                </div>
                                                </td>
                                                
                             
                
                                    </tr>
                                    @php($i++)
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>

        </div>
    </section>
    <!-- /.content -->

@endsection